services:
  - type: web
    name: petrol-station-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production