"""Add missing columns to pumps and create stations table

Revision ID: 01714955afe0
Revises: c9a732306990
Create Date: 2025-09-24 00:46:27.034071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01714955afe0'
down_revision = 'c9a732306990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=False, server_default='Regular'))
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.alter_column('pump_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_pumps_station_id', 'stations', ['station_id'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='Employee'))
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('position')

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stations_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stations_name', type_='unique')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('role')

    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pumps_station_id', type_='foreignkey')
        batch_op.alter_column('pump_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('station_id')
        batch_op.drop_column('fuel_type')
    # ### end Alembic commands ###
