"""Remove contribution from sales

Revision ID: 5478a5afde93
Revises: b244d699a449
Create Date: 2025-09-24 11:14:15.054876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5478a5afde93'
down_revision = 'b244d699a449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sales', schema=None) as batch_op:
        batch_op.drop_column('contribution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
