"""update pump_number field length and add validation

Revision ID: 6ce1d72bdcef
Revises: 3d279e0b7bf4
Create Date: 2025-09-24 16:29:01.689376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce1d72bdcef'
down_revision = '3d279e0b7bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.alter_column('pump_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.alter_column('pump_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
